apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    release: prometheus
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kube-scheduler
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: https-metrics
      scheme: https
      interval: 30s
      scrapeTimeout: 10s
      tlsConfig:
        insecureSkipVerify: true
