apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: scientific-workflow
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx128M"
            - name: SERVER_PORT
              value: "9000"
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: scientific-workflow
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: kafdrop