apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: scientific-workflow
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.12
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: scientific-workflow
data:
  redis.conf: |
    notify-keyspace-events Ex
    maxmemory 256mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: scientific-workflow
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
