apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-test-
  namespace: scientific-workflow
spec:
  entrypoint: write-artifact
  templates:
    - name: write-artifact
      container:
        image: alpine
        command: [sh, -c]
        args: ["echo 'Hello from Argo!' > /tmp/hello.txt"]
      outputs:
        artifacts:
          - name: hello-artifact
            path: /tmp/hello.txt