apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: generate-text-file-template
spec:
  entrypoint: generate-file

  templates:
  - name: generate-file
    outputs:
      artifacts:
      - name: hello-file
        path: /tmp/hello.txt
    container:
      image: alpine:3.18
      command: [sh, -c]
      args:
        - echo "Hello, Argo!" > /tmp/hello.txt