import React from 'react';
import { Alert, Box, Divider, Paper, Typography } from '@mui/material';
import { useAuth } from '../../contexts/AuthContext';

function StorageInfo() {
  const { user } = useAuth();
  const userId = user?._id;
  
  return (
    <>
      <Typography variant="h6" gutterBottom>
        Storage Information
      </Typography>
      <Divider sx={{ mb: 2 }} />
      
      <Alert severity="info" sx={{ mb: 2 }}>
        You are only able to access your personal folders and public folders.
      </Alert>
      
      <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
        <Typography variant="subtitle1" fontWeight="bold" gutterBottom>
          Your personal folders:
        </Typography>
        <Box component="ul" sx={{ pl: 2, mt: 1 }}>
          <li><Typography variant="body2"><strong>{userId}/input/</strong> - Store files to be used as inputs for workflows</Typography></li>
          <li><Typography variant="body2"><strong>{userId}/output/</strong> - Access files generated by workflows</Typography></li>
          <li><Typography variant="body2"><strong>{userId}/scripts/</strong> - Store files to be used for scripts by workflows</Typography></li>
        </Box>
      </Paper>
      
      <Paper variant="outlined" sx={{ p: 2 }}>
        <Typography variant="subtitle1" fontWeight="bold" gutterBottom>
          Public folders:
        </Typography>
        <Box component="ul" sx={{ pl: 2, mt: 1 }}>
          <li><Typography variant="body2"><strong>public/input/</strong> - Access shared input files</Typography></li>
          <li><Typography variant="body2"><strong>public/output/</strong> - Access shared output files</Typography></li>
          <li><Typography variant="body2"><strong>public/scripts/</strong> - Access shared scripts files</Typography></li>
        </Box>
      </Paper>
      
      <Typography variant="body2" sx={{ mt: 2 }}>
        Files in these locations are accessible to your workflows via the Minio endpoint.
      </Typography>
    </>
  );
}

export default StorageInfo;