{
 "title": "Argo Dashboard",
 "description": "This dashboard displays all the relevant metrics related to argo workflows.",
 "tags": [
  "Argo",
  "Argo Workflows"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Workflow",
    "query": {
     "query": "query_result(kube_pod_status_phase{namespace=\"scientific-workflow\", phase=\"Running\", pod=~\"lisa-workflow-.*\"} == 1)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Running Workflow Count",
   "type": "stat",
   "description": "The total number of currently running workflows. This is a real-time indicator of concurrency and load on the system.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  argo_workflows_gauge{\n    status=\"Running\", namespace=\"scientific-workflow\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Status Breakdown",
   "type": "piechart",
   "description": "Shows the number of workflows in each status: Running, Succeeded, Failed, etc. Good for tracking success/failure rates.",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\n  argo_workflows_gauge{namespace=\"scientific-workflow\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Argo Workflows Version",
   "type": "table",
   "description": "This metric reports the version of the Argo Workflows controller running in the scientific-workflow namespace. It helps verify that the correct version is deployed and can be used for tracking version changes across updates or debugging compatibility issues with workflows.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "argo_workflows_version{namespace=\"scientific-workflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Authors",
   "type": "table",
   "description": "This panel displays a custom metric that is exposed through Pipeline Runner backend application and it shows the author who initiated the workflow. The author metric is exposed when a workflow is launched through the Pipeline Runner UI and the data of the user that is registered in the Pipeline Runner is used. This will not work if the workflow is submitted directly through Argo UI.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "argo_workflows_created_by{namespace=\"scientific-workflow\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Workflows",
   "type": "table",
   "description": "This panel shows the number pods that have terminated with the reason \"Completed\", indicating successful execution. It is commonly used to track the number of successfully finished tasks or workflows—such as in Argo Workflows—within the cluster. Useful for monitoring workload throughput and success rates.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{reason=\"Completed\", container=\"main\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Error Logs",
   "type": "logs",
   "description": "Displays logs from pods where the name begins with lisa-workflow and shows logs with level \"error\" and \"fatal\" or shows the logs where an exit status was shown",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{pod=~\"lisa-workflow.*\", container=\"main\"} |= \"exit status\""
    },
    {
     "direction": "backward",
     "expr": "{pod=~\"lisa-workflow.*\"} |= \"level=error\""
    },
    {
     "direction": "backward",
     "expr": "{pod=~\"lisa-workflow.*\"} |= \"level=fatal\""
    }
   ]
  },
  {
   "title": "Errored Workflows",
   "type": "table",
   "description": "Displays workflows that were finished with an error or a fail reason",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{reason!=\"Completed\", container=\"main\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Uptime - ${Workflow}",
   "type": "stat",
   "description": "Duration since the pod was started. Helps identify long-running steps or stuck workflow components.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "repeat": "Workflow",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_pod_start_time{namespace=\"scientific-workflow\", pod=~\"${Workflow:regex}|^$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Logs - ${Workflow}",
   "type": "logs",
   "description": "Displays logs from workflow pods. Replicates individually for each workflow",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "repeat": "Workflow",
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"scientific-workflow\", pod=~\"${Workflow:regex}|^$\"}"
    }
   ]
  },
  { "title": "Workflow RAM Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Workflow RAM Consumption",
   "type": "timeseries",
   "description": "This panel shows the memory usage rate (working set) of individual Argo workflow pods in the scientific-workflow namespace over the set period time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"scientific-workflow\", pod=~\"lisa-workflow-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflow Pod Memory Usage - ${Workflow}",
   "type": "gauge",
   "description": "Displays the current memory usage (excluding page cache) for each active workflow pod in the scientific-workflow namespace. Reflects the actual memory pressure experienced by containers.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "repeat": "Workflow",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(pod) (\n  container_memory_usage_bytes{\n    container=\"main\",\n    namespace=\"scientific-workflow\",\n    pod=~\"${Workflow:regex}|^$\"\n  }\n)\n/\nsum by(pod) (\n  kube_pod_container_resource_limits{\n    namespace=\"scientific-workflow\",\n    resource=\"memory\",\n    unit=\"byte\",\n    pod=~\"${Workflow:regex}|^$\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workflow CPU Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Workflow CPU Usage",
   "type": "timeseries",
   "description": "This graph displays the CPU usage of each running Argo workflow. \nThe graph allows to see historically how much CPU resource each workflow consumed",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"scientific-workflow\", pod=~\"lisa-workflow-.*\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage - ${Workflow}",
   "type": "gauge",
   "description": "This panel displays the real-time CPU usage of each running Argo workflow pod in the scientific-workflow namespace, expressed as a percentage of its defined CPU limit. It uses the rate() function over a 2-minute window to calculate CPU usage in cores, and divides it by the pod’s CPU resource limit using a Prometheus on(pod, namespace) join. The result is multiplied by 100 to show CPU usage as a percentage. The panel dynamically repeats for each active workflow, providing a live view of how much of its allocated CPU each pod is consuming.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "repeat": "Workflow",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nrate(container_cpu_usage_seconds_total{\n  container=\"main\",\n  namespace=\"scientific-workflow\",\n  pod=~\"${Workflow:regex}|^$\"\n}[2m])\n/\non(pod, namespace)\nkube_pod_container_resource_limits{\n  container=\"main\",\n  resource=\"cpu\",\n  namespace=\"scientific-workflow\",\n  pod=~\"${Workflow:regex}|^$\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk I/O Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "description": " Total read throughput from the container’s file system, in bytes/sec. Useful to detect read-heavy workloads or disk-bound steps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_fs_reads_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"${Workflow:regex}|^$\"\n  }[1m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "description": "Total write throughput to the container’s file system, in bytes/sec. Indicates workflows writing large results or logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_fs_writes_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"${Workflow:regex}|^$\"\n  }[1m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network I/O Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Network Outbound Rate",
   "type": "timeseries",
   "description": "Rate of bytes sent over the network from the container. Useful for identifying workflows that send data to remote services or distributed systems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_network_transmit_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"${Workflow:regex}|^$\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Inbound Rate",
   "type": "timeseries",
   "description": "Rate of bytes received over the network by the container. Helps detect workflows that fetch data from APIs, storage systems, or databases.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_network_receive_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"${Workflow:regex}|^$\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}