{
 "title": "Historic Dashboard",
 "tags": [ "Historic" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflow RAM Consumption",
   "type": "timeseries",
   "description": "This panel displays the real-time memory usage for each lisa-workflow-* pod in the scientific-workflow namespace.\nIt uses the rate() function over a 1-minute window on the container_memory_working_set_bytes metric to estimate how quickly memory consumption is changing, and groups the data by pod. This provides insights into the working set memory (i.e., actively used memory) of each Argo workflow pod, helping to detect high or abnormal memory usage patterns. ",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"scientific-workflow\", pod=~\"lisa-workflow-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow CPU Usage",
     "type": "timeseries",
     "description": "This panel displays the real-time CPU usage for each lisa-workflow-* pod in the scientific-workflow namespace.\nIt uses the rate() function over a 1-minute window on the container_cpu_usage_seconds_total metric to calculate the per-second CPU usage in cores, grouped by pod. This provides a view of how much CPU each Argo workflow pod was consuming.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"scientific-workflow\", pod=~\"lisa-workflow-.*\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root FS Used",
     "type": "timeseries",
     "description": "This panel shows the average percentage of used disk space for each mountpoint, excluding the rootfs filesystem.\nHelps monitor how full each disk is across nodes, so storage issues can be spotted early.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(\n  (\n    (node_filesystem_size_bytes{ fstype!=\"rootfs\"}\n     - node_filesystem_avail_bytes{ fstype!=\"rootfs\"})\n    / node_filesystem_size_bytes{ fstype!=\"rootfs\"}\n  ) * 100\n) by (mountpoint)\n"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network Inbound Rate",
   "type": "timeseries",
   "description": "Rate of bytes received over the network by the container. Helps detect workflows that fetch data from APIs, storage systems, or databases.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_network_receive_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"lisa-workflow-.*\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Outbound Rate",
   "type": "timeseries",
   "description": "Rate of bytes sent over the network from the container. Useful for identifying workflows that send data to remote services or distributed systems.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_network_transmit_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"lisa-workflow-.*\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "description": " Total read throughput from the container’s file system, in bytes/sec. Useful to detect read-heavy workloads or disk-bound steps.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_fs_reads_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"lisa-workflow-.*\"\n  }[1m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "description": "Total write throughput to the container’s file system, in bytes/sec. Indicates workflows writing large results or logs.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(container_fs_writes_bytes_total{\n    namespace=\"scientific-workflow\",\n    pod=~\"lisa-workflow-.*\"\n  }[1m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}