{
 "title": "Kubernetes Dashboard",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "K8S",
    "query": {
     "query": "label_values(kube_node_info,origin_prometheus)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{origin_prometheus=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\", container=~\"$Container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes/ node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_size_bytes{mountpoint=\"/var\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{mountpoint=\"/var\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{mountpoint=\"/var\", fstype!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/var\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resource Overview：$Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
     "repeat": "origin_prometheus",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "count(kube_pod_info)", "legendFormat": "Total pods" },
      {
       "expr": "count(kube_pod_info{namespace=\"scientific-workflow\"})",
       "legendFormat": "Workflow Pods"
      },
      {
       "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{origin_prometheus=~\"$origin_prometheus\",key=~\"node.kubernetes.io.*\"})",
       "legendFormat": "{{key}}"
      },
      { "expr": "count(kube_node_info)", "legendFormat": "Total Nodes" },
      {
       "expr": "sum(\n  argo_workflows_gauge{\n    namespace=\"scientific-workflow\",\n    status=\"Running\"\n  }\n)",
       "legendFormat": "Running Workflows Count"
      }
     ]
    },
    {
     "title": "Node Memory Information",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Node CPU Ratio",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU Utilization Rate"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU Request Rate"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU Limit Rate"
      }
     ]
    },
    {
     "title": "Nodes with Pod",
     "type": "bargauge",
     "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "count(kube_node_info)", "legendFormat": "Number of nodes" },
      {
       "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
       "legendFormat": "Pod Number of nodes"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
       "legendFormat": "Upper limit Pod"
      }
     ]
    },
    {
     "title": "Node Memory Ratio",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Memory Request Rate"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Memory Limit Rate"
      }
     ]
    },
    {
     "title": "Node CPU Number of cores",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "Total Cores"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Node Storage Information",
     "type": "bargauge",
     "description": "This graph will need to be adjusted for real deployment because local dev env is hosted through kind which does not allow access to real disk metrics.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(\n  node_filesystem_size_bytes{mountpoint=\"/var\"}\n  - node_filesystem_free_bytes{mountpoint=\"/var\"}\n)\n/\nsum(\n  node_filesystem_size_bytes{mountpoint=\"/var\"}\n)",
       "legendFormat": "Utilization Rate"
      },
      {
       "expr": "sum(\n  node_filesystem_size_bytes{mountpoint=\"/var\"}\n  - node_filesystem_free_bytes{mountpoint=\"/var\"}\n)",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(\n  node_filesystem_size_bytes{mountpoint=\"/var\"}\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$NameSpace：Network Overview（Associable nodes and namespaces）",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum (irate(container_network_receive_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum (irate(container_network_transmit_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Memory Usage【$Node】",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU Used Cores【$Node】",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "Total Cores"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Pod Number and nodes【$Node】",
     "type": "timeseries",
     "description": "Number of Cluster Nodes，Nodes POD Number of，Nodes POD Upper Limit",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "count(kube_node_info)", "legendFormat": "Number of nodes" },
      {
       "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
       "legendFormat": "Pod Number"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
       "legendFormat": "Upper Limit Pod"
      }
     ]
    },
    {
     "title": "$Node：Nodes CPU Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)*100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$Node：Node Memory Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)*100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$Node：Node Network Overview",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum (irate(container_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
       "legendFormat": "Inflow:{{node}}"
      },
      {
       "expr": "sum (irate(container_network_transmit_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
       "legendFormat": "Outflows:{{node}}"
      }
     ]
    },
    {
     "title": "$Node：Node Information Detail",
     "type": "table",
     "description": "Once again, disk usage needs to be adjusted once deployed",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
       "legendFormat": "pod Number"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) by (node)"
      },
      {
       "expr": "kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Usage%"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Requests%"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Limit%"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU Usage%"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU Requests%"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Limit%"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "Disk Usage%"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "PodCaps"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Resource Overview：SelectedPod:【 $Pod 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Containers CPU Utilization ( Maximum 100% Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(\n  irate(container_cpu_usage_seconds_total{\n    pod=~\"$Pod\",\n    container=~\"$Container\",\n    container!=\"\",\n    container!=\"POD\",\n    node=~\"^$Node$\",\n    namespace=~\"$NameSpace\"\n  }[2m])\n) by (container, pod)\n/ \nmax(\n  kube_pod_container_resource_limits{\n    resource=\"cpu\",\n    unit=\"core\",\n    pod=~\"$Pod\",\n    container=~\"$Container\",\n    namespace=~\"$NameSpace\"\n  }\n) by (container, pod)\n* 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod Container Memory Usage (Associatable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(\n  container_memory_working_set_bytes{\n    origin_prometheus=~\"$origin_prometheus\",\n    pod=~\"$Pod\",\n    container=~\"$Container\",\n    container!=\"\", container!=\"POD\",\n    node=~\"^$Node$\",\n    namespace=~\"$NameSpace\"\n  }\n) by (container, pod)\n/ \nmax(\n  kube_pod_container_resource_limits{\n    origin_prometheus=~\"$origin_prometheus\",\n    pod=~\"$Pod\",\n    container=~\"$Container\",\n    resource=\"memory\",\n    unit=\"byte\",\n    namespace=~\"$NameSpace\"\n  }\n) by (container, pod)\n* 100",
       "legendFormat": "WSS：{{ pod }}"
      },
      {
       "expr": "max (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "RSS：{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod Network bandwidth per second (Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "max(max(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
       "legendFormat": "Inflow:{{ pod}}"
      },
      {
       "expr": "max(max(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
       "legendFormat": "Outflow:{{ pod}}"
      }
     ]
    },
    {
     "title": "Pod Containers CPU Core Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "CPU Usage：{{ pod }}"
      },
      {
       "expr": "max(max(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
       "legendFormat": "Pod CPU Limitations：{{ container}}"
      }
     ]
    },
    {
     "title": "Pod Containers WSS Memory Usage (Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
       "legendFormat": "WSS：{{ pod }}"
      },
      {
       "expr": "max(max(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
       "legendFormat": "PodMemory Limits：{{ container}}"
      }
     ]
    },
    {
     "title": "Pod Containers RSS Memory Usage (Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
       "legendFormat": "RSS：{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}